### ISSUE TITLE
yolov6的模型转tensorrt，可以搞成c++的吗？

### ISSUE THREAD

**Issue by xinsuinizhuan** [Linaom1214/tensorrt-python#1]
像大神的：https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5
或者：https://github.com/shouxieai/tensorRT_Pro

**Comment by Linaom1214** [comment]
> 像大神的：https://github.com/wang-xinyu/tensorrtx/tree/master/yolov5

本项目就有C++实现呀，tensorrtx 是真大佬，我这是采用onnx到trt 本质上和tensorRT Pro的实现方式一样

**Comment by xinsuinizhuan** [comment]
另外，推理和解码都是在cpu上跑的，预处理和后处理，需要优化的地方还比较多。

**Comment by Linaom1214** [comment]
> 另外，推理和解码都是在cpu上跑的，预处理和后处理，需要优化的地方还比较多。

这里只是简单的代码实现，您可以基于此二次开发

**Comment by Linaom1214** [comment]
> Jun
更新了新的end2end 方案，无需第三库更简洁高效，enjoy it!

**Comment by xinsuinizhuan** [comment]
> > Jun
> > 更新了新的end2end 方案，无需第三库更简洁高效，enjoy it!

地址发一下！

**Comment by Linaom1214** [comment]
> > > Jun
> > > 更新了新的end2end 方案，无需第三库更简洁高效，enjoy it!
> 
> 地址发一下！

https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/main/Examples.ipynb
