### ISSUE TITLE
yolox官方模型导出，进行推理时无检测结果

### ISSUE THREAD

**Issue by PL2584718785** [Linaom1214/tensorrt-python#11]
您好，大佬 麻烦请教下

使用的官方模型为 https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_s.pth / https://github.com/Megvii-BaseDetection/storage/releases/download/0.0.1/yolox_s.pth  这两个版本的

按照您的如下教程 修改后：
```
修改 export_onnx.py 为 model.head.decode_in_inference = True

修改 yolox/models/yolox_head.py文件

# [batch, n_anchors_all, 85]
# outputs = torch.cat(
#     [x.flatten(start_dim=2) for x in outputs], dim=2

# ).permute(0, 2, 1)
outputs = torch.cat(
    [x.view(-1,int(x.size(1)),int(x.size(2)*x.size(3))) for x in outputs], dim=2

).permute(0, 2, 1)

# outputs[..., :2] = (outputs[..., :2] + grids) * strides
# outputs[..., 2:4] = torch.exp(outputs[..., 2:4]) * strides
# return outputs
xy =  (outputs[..., :2] + grids) * strides
wh = torch.exp(outputs[..., 2:4]) * strides
return torch.cat((xy, wh, outputs[..., 4:]), dim=-1) 
```

可以生成.onnx文件，然后 转换tensorrt引擎(fp32) 都成功

但是运行trt.py文件 后，图片无检测结果，打印dets 显示为None， 请问下是什么原因呢 ？  望解答，非常感谢

**Comment by Linaom1214** [comment]
> 

我也发现了这个问题，目前在解决，我用的是最早一个版本的yolox，先是这将
https://github.com/Linaom1214/tensorrt-python/blob/5433b4d5cf011cf647bea26e706b9987f667beb0/utils/utils.py#L190
这一行注释掉，如果可以起到作用的话感谢反馈

**Comment by PL2584718785** [comment]
> > 
> 
> 我也发现了这个问题，目前在解决，我用的是最早一个版本的yolox，先是这将
> 
> https://github.com/Linaom1214/tensorrt-python/blob/5433b4d5cf011cf647bea26e706b9987f667beb0/utils/utils.py#L190
> 
> 
> 这一行注释掉，如果可以起到作用的话感谢反馈


好的，非常感谢大佬的回复
我已经按照您的方法进行了尝试，但还是失败的：
使用的最初版yolox的.pth(0.1.0版本)，进行转换得到.trt  最后遇到下面问题
1）注释预处理里面的代码行 padded_img /= 255.0 ，初始化设置均值和方差为None，图片的检测结果也是什么都没有；
2）注释预处理里面的代码行 padded_img /= 255.0，初始化设置均值和方差的值，图片中有检测框，但是很乱且与目标不匹配；

**请大佬解答下，打扰啦，非常感谢！**

**Comment by Linaom1214** [comment]
> 

可以先试着用0.1.0版的代码进行onnx导出，对我的代码不做修改试试，暂时不清楚yolox以后的版本修改了哪些部分，我打算在周末解决这个问题。

**Comment by Linaom1214** [comment]
> > > 
> > 
> > 
> > 我也发现了这个问题，目前在解决，我用的是最早一个版本的yolox，先是这将
> > https://github.com/Linaom1214/tensorrt-python/blob/5433b4d5cf011cf647bea26e706b9987f667beb0/utils/utils.py#L190
> > 
> > 这一行注释掉，如果可以起到作用的话感谢反馈
> 
> 好的，非常感谢大佬的回复 我已经按照您的方法进行了尝试，但还是失败的： 使用的最初版yolox的.pth(0.1.0版本)，进行转换得到.trt 最后遇到下面问题 1）注释预处理里面的代码行 padded_img /= 255.0 ，初始化设置均值和方差为None，图片的检测结果也是什么都没有； 2）注释预处理里面的代码行 padded_img /= 255.0，初始化设置均值和方差的值，图片中有检测框，但是很乱且与目标不匹配；
> 
> **请大佬解答下，打扰啦，非常感谢！**

新版本修复了这个问题：

使用YOLOX模型时 请注释掉

```
    padded_img = padded_img[:, :, ::-1]
    padded_img /= 255.0
```

https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/adc89037992522d81d3ca349edad62eecf7edd9e/utils/utils.py#L201

**Comment by QzYER** [comment]
yolov5l用export转成engine之后也是没有检测结果。但是检测的out能看到种类，box，置信度这些信息，其中置信度是负数。
