### ISSUE TITLE
yolov7-tiny onnx -> engine 报错

### ISSUE THREAD

**Issue by GZXB-1997** [Linaom1214/tensorrt-python#14]
利用官方yolov7-tiny.pt转onnx可顺利运行
但是在onnx -> engine 过程中报错

Failed to load ONNX file: /home/user/05.yolov7/yolov7-tiny.onnx
In node 67 (parseGraph): INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName)

请问楼主遇到过相同的问题吗？

**Comment by Linaom1214** [comment]
> 利用官方yolov7-tiny.pt转onnx可顺利运行 但是在onnx -> engine 过程中报错
> 
> Failed to load ONNX file: /home/user/05.yolov7/yolov7-tiny.onnx In node 67 (parseGraph): INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName)
> 
> 请问楼主遇到过相同的问题吗？

torch版本是最新的吗？
