### ISSUE TITLE
ONNX export failure: Exporting the operator silu to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator

### ISSUE THREAD

**Issue by lthbk5919** [Linaom1214/tensorrt-python#16]
I get error

> ONNX export failure: Exporting the operator silu to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator

 when run script `python3 models/export.py --weights ../yolov7.pt --grid`

Help me!!!

**Comment by Linaom1214** [comment]
> I get error
> 
> > ONNX export failure: Exporting the operator silu to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator
> 
> when run script `python3 models/export.py --weights ../yolov7.pt --grid`
> 
> Help me!!!

update torch version

**Comment by lthbk5919** [comment]
Thank @Linaom1214 !!!
This issue has been resolved.
