### ISSUE TITLE
yolox decode

### ISSUE THREAD

**Issue by ygygyeah** [Linaom1214/tensorrt-python#19]
您好，我想请教一下。在您的代码中，yolox在infer之后为什么没有进行decode操作，而是直接进行postprocess呢？
![image](https://user-images.githubusercontent.com/47774299/182088416-733bd7b5-2803-446d-a951-399df6fcfa7d.png)

**Comment by Linaom1214** [comment]
> 您好，我想请教一下。在您的代码中，yolox在infer之后为什么没有进行decode操作，而是直接进行postprocess呢？ ![image](https://user-images.githubusercontent.com/47774299/182088416-733bd7b5-2803-446d-a951-399df6fcfa7d.png)

decode部分已经整合到onnx模型中了

**Comment by ygygyeah** [comment]
好的，谢谢！

**Comment by leomy9527** [comment]
> > 您好，我想请教一下。在您的代码中，yolox在infer之后为什么没有进行decode操作，而是直接进行postprocess呢？ ![image](https://user-images.githubusercontent.com/47774299/182088416-733bd7b5-2803-446d-a951-399df6fcfa7d.png)
> 
> decode部分已经整合到onnx模型中了

大佬 能补全一下decode吗  我使用别人的模型 没法整合了

**Comment by leomy9527** [comment]
> > 您好，我想请教一下。在您的代码中，yolox在infer之后为什么没有进行decode操作，而是直接进行postprocess呢？ ![image](https://user-images.githubusercontent.com/47774299/182088416-733bd7b5-2803-446d-a951-399df6fcfa7d.png)
> 
> decode部分已经整合到onnx模型中了

大佬 能补全一下decode吗 我使用别人的模型 没法整合了,谢谢
