### ISSUE TITLE
imgs order

### ISSUE THREAD

**Issue by ygygyeah** [Linaom1214/tensorrt-python#21]
您好，我想问一下：
这里的imgsz的值对应着（宽、高）还是（高、宽）呢？
![image](https://user-images.githubusercontent.com/47774299/182343493-eb9eeb16-2d10-4201-884d-b7f1314cbce7.png)

**Comment by Linaom1214** [comment]
> 您好，我想问一下： 这里的imgsz的值对应着（宽、高）还是（高、宽）呢？ ![image](https://user-images.githubusercontent.com/47774299/182343493-eb9eeb16-2d10-4201-884d-b7f1314cbce7.png)

same as Opencv Data fromat
