### ISSUE TITLE
what's your tensorrt version?

### ISSUE THREAD

**Issue by h030162** [Linaom1214/tensorrt-python#3]
command:
python export_trt.py -m ../weights/yolov6s.onnx -o yolov6s.trt

error:
[TensorRT] VERBOSE: ModelImporter.cpp:129: Reshape_214 [Reshape] inputs: [411 -> (1, 1, 20, 20, 85)], [467 -> (3)], 
[TensorRT] VERBOSE: ImporterContext.hpp:122: Registering layer: Reshape_214 for ONNX node: Reshape_214
[TensorRT] VERBOSE: ImporterContext.hpp:97: Registering tensor: 418 for ONNX tensor: 418
[TensorRT] VERBOSE: ModelImporter.cpp:180: Reshape_214 [Reshape] outputs: [418 -> (1, 400, 85)], 
[TensorRT] VERBOSE: ModelImporter.cpp:107: Parsing node: Concat_215 [Concat]
[TensorRT] VERBOSE: ModelImporter.cpp:123: Searching for input: 302
[TensorRT] VERBOSE: ModelImporter.cpp:123: Searching for input: 360
[TensorRT] VERBOSE: ModelImporter.cpp:123: Searching for input: 418
[TensorRT] VERBOSE: ModelImporter.cpp:129: Concat_215 [Concat] inputs: [302 -> (1, 6400, 85)], [360 -> (1, 1600, 85)], [418 -> (1, 400, 85)], 
[TensorRT] VERBOSE: ImporterContext.hpp:122: Registering layer: Concat_215 for ONNX node: Concat_215
[TensorRT] VERBOSE: ImporterContext.hpp:97: Registering tensor: outputs_1 for ONNX tensor: outputs
[TensorRT] VERBOSE: ModelImporter.cpp:180: Concat_215 [Concat] outputs: [outputs -> (1, 8400, 85)], 
[TensorRT] VERBOSE: ModelImporter.cpp:494: Marking outputs_1 as output: outputs
Traceback (most recent call last):
  File "export_trt.py", line 54, in <module>
    engine = builder.build_serialized_network(network,config)
AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'build_serialized_network'

my tensorrt version is 7.0.0.11

**Comment by Linaom1214** [comment]
8.2.0.4
