### ISSUE TITLE
infer time

### ISSUE THREAD

**Issue by h030162** [Linaom1214/tensorrt-python#6]
1.What's your gpu type?
2.What's single image infer time of the yolov6s.trt and yolov7.trt?
The author said yolov7 was faster, but it was not so when I tested it.
In my test:
yolov6s : 14ms
yolov7: about 40ms
gpu:GeForce GTX 1060
Driver Version: 455.28

**Comment by Linaom1214** [comment]
> 1.What's your gpu type? 2.What's single image infer time of the yolov6s.trt and yolov7.trt? The author said yolov7 was faster, but it was not so when I tested it. In my test: yolov6s : 14ms yolov7: about 40ms gpu:GeForce GTX 1060 Driver Version: 455.28

you can use tiny model to report the fps

**Comment by Linaom1214** [comment]
> > 1.What's your gpu type? 2.What's single image infer time of the yolov6s.trt and yolov7.trt? The author said yolov7 was faster, but it was not so when I tested it. In my test: yolov6s : 14ms yolov7: about 40ms gpu:GeForce GTX 1060 Driver Version: 455.28
> 
> you can use tiny model to report the fps
 my pc is 1080TI
