### ISSUE TITLE
trt 部署

### ISSUE THREAD

**Issue by gy-zkj** [Linaom1214/tensorrt-python#7]
大佬你好，
我按照readme里边将yolo.py对应代码改成：
return x if self.training else (torch.cat(z, 1), ) if not self.export else (torch.cat(z, 1), x)
然后训练的时候每次训练1个epoch就报这个错误

File "/home/yolov7/yolov7/test.py", line 110, in test
    out, train_out = model(img, augment=augment)  # inference and training outputs
ValueError: not enough values to unpack (expected 2, got 1)

假如不改这一块转换的onnx无法转出engine

**Comment by Linaom1214** [comment]
> 如不改这一块转换的onnx无法转出engine
导出的时候再修改，修改是为了得到只有一个输出的onnx模型

**Comment by gy-zkj** [comment]
感谢大佬 马上去试试

**Comment by BandyKenny** [comment]
我发现转的错误：
CoreML export failure: PyTorch convert function for op 'silu_' not implemented.
这个怎么改呀

**Comment by Linaom1214** [comment]
> CoreML

如果不需要苹果设备部署的话，不需要关注这一条错误，这倒是导出苹果部署模型出错了

**Comment by mickey-cool** [comment]
> 
我也遇到这个错误了，请问解决了么

**Comment by Linaom1214** [comment]
> Converting op 1570 : slice Adding op '1570' of type slice_by_index Adding op '1570_begin_0' of type const Adding op '1570_end_0' of type const Adding op '1570_end_mask_0' of type const Converting op y.1_internal_tensor_assign_1 : _internal_op_tensor_inplace_copy Adding op 'y.1_internal_tensor_assign_1' of type torch_tensor_assign Adding op 'y.1_internal_tensor_assign_1_begin_0' of type const Adding op 'y.1_internal_tensor_assign_1_end_0' of type const Adding op 'y.1_internal_tensor_assign_1_stride_0' of type const Adding op 'y.1_internal_tensor_assign_1_begin_mask_0' of type const Adding op 'y.1_internal_tensor_assign_1_end_mask_0' of type const Adding op 'y.1_internal_tensor_assign_1_squeeze_mask_0' of type const Converting Frontend ==> MIL Ops: 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 1118/1200 [00:00<00:00, 2597.59 ops/s] CoreML export failure: The updates tensor should have shape (1, 3, 80, 80, 15). Got (1, 3, 80, 80, 2)
> 
> 我也遇到这个错误了，请问解决了么

据我所知这个报错和onnx无关啊

**Comment by mickey-cool** [comment]
> > Converting op 1570 : slice Adding op '1570' of type slice_by_index Adding op '1570_begin_0' of type const Adding op '1570_end_0' of type const Adding op '1570_end_mask_0' of type const Converting op y.1_internal_tensor_assign_1 : _internal_op_tensor_inplace_copy Adding op 'y.1_internal_tensor_assign_1' of type torch_tensor_assign Adding op 'y.1_internal_tensor_assign_1_begin_0' of type const Adding op 'y.1_internal_tensor_assign_1_end_0' of type const Adding op 'y.1_internal_tensor_assign_1_stride_0' of type const Adding op 'y.1_internal_tensor_assign_1_begin_mask_0' of type const Adding op 'y.1_internal_tensor_assign_1_end_mask_0' of type const Adding op 'y.1_internal_tensor_assign_1_squeeze_mask_0' of type const Converting Frontend ==> MIL Ops: 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 1118/1200 [00:00<00:00, 2597.59 ops/s] CoreML export failure: The updates tensor should have shape (1, 3, 80, 80, 15). Got (1, 3, 80, 80, 2)
> > 我也遇到这个错误了，请问解决了么
> 
> 据我所知这个报错和onnx无关啊

[07/20/2022-15:17:25] [TRT] [I] [MemUsageChange] Init CUDA: CPU +450, GPU +0, now: CPU 477, GPU 5540 (MiB)
[07/20/2022-15:17:25] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 477 MiB, GPU 5540 MiB
[07/20/2022-15:17:25] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 631 MiB, GPU 5584 MiB
[07/20/2022-15:17:25] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[07/20/2022-15:17:25] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[07/20/2022-15:17:25] [TRT] [E] [graphShapeAnalyzer.cpp::analyzeShapes::1285] Error Code 4: Miscellaneous (IElementWiseLayer Mul_378: broadcast dimensions must be conformable)
Failed to load ONNX file: /media/yolov7/cfg/deploy/yolov7.onnx
In node 378 (parseGraph): INVALID_NODE: Invalid Node - Mul_378
[graphShapeAnalyzer.cpp::analyzeShapes::1285] Error Code 4: Miscellaneous (IElementWiseLayer Mul_378: broadcast dimensions must be conformable)


没管刚刚那个错误，用转出来的onnx去转tensorrt报了这个错

**Comment by Linaom1214** [comment]
> > > Converting op 1570 : slice Adding op '1570' of type slice_by_index Adding op '1570_begin_0' of type const Adding op '1570_end_0' of type const Adding op '1570_end_mask_0' of type const Converting op y.1_internal_tensor_assign_1 : _internal_op_tensor_inplace_copy Adding op 'y.1_internal_tensor_assign_1' of type torch_tensor_assign Adding op 'y.1_internal_tensor_assign_1_begin_0' of type const Adding op 'y.1_internal_tensor_assign_1_end_0' of type const Adding op 'y.1_internal_tensor_assign_1_stride_0' of type const Adding op 'y.1_internal_tensor_assign_1_begin_mask_0' of type const Adding op 'y.1_internal_tensor_assign_1_end_mask_0' of type const Adding op 'y.1_internal_tensor_assign_1_squeeze_mask_0' of type const Converting Frontend ==> MIL Ops: 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 1118/1200 [00:00<00:00, 2597.59 ops/s] CoreML export failure: The updates tensor should have shape (1, 3, 80, 80, 15). Got (1, 3, 80, 80, 2)
> > > 我也遇到这个错误了，请问解决了么
> > 
> > 
> > 据我所知这个报错和onnx无关啊
> 
> [07/20/2022-15:17:25] [TRT] [I] [MemUsageChange] Init CUDA: CPU +450, GPU +0, now: CPU 477, GPU 5540 (MiB) [07/20/2022-15:17:25] [TRT] [I] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 477 MiB, GPU 5540 MiB [07/20/2022-15:17:25] [TRT] [I] [MemUsageSnapshot] End constructing builder kernel library: CPU 631 MiB, GPU 5584 MiB [07/20/2022-15:17:25] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32. [07/20/2022-15:17:25] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped [07/20/2022-15:17:25] [TRT] [E] [graphShapeAnalyzer.cpp::analyzeShapes::1285] Error Code 4: Miscellaneous (IElementWiseLayer Mul_378: broadcast dimensions must be conformable) Failed to load ONNX file: /media/yolov7/cfg/deploy/yolov7.onnx In node 378 (parseGraph): INVALID_NODE: Invalid Node - Mul_378 [graphShapeAnalyzer.cpp::analyzeShapes::1285] Error Code 4: Miscellaneous (IElementWiseLayer Mul_378: broadcast dimensions must be conformable)
> 
> 没管刚刚那个错误，用转出来的onnx去转tensorrt报了这个错

Pytorch 版本的问题升级到最新版解决
