### ISSUE TITLE
请问下tensorrt版本 

### ISSUE THREAD

**Issue by axxx-xxxa** [Linaom1214/tensorrt-python#8]
![1657696105306](https://user-images.githubusercontent.com/79968824/178672467-c4b1d780-0279-4e7a-90c5-00caa6e9179a.png)

onnx转换trt是OK的

**Comment by axxx-xxxa** [comment]
![1657698775885](https://user-images.githubusercontent.com/79968824/178680785-3a475d7f-0997-49f2-9521-338909e6d493.png)

**Comment by Linaom1214** [comment]
> ![1657698775885](https://user-images.githubusercontent.com/79968824/178680785-3a475d7f-0997-49f2-9521-338909e6d493.png)

确认一下的类别数有没有修改，同时检查一下numpy 版本是不是小于1.9
